In [1]:
import pandas as pd
import numpy as np

import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

import warnings
warnings.filterwarnings("ignore")

In [2]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\creat\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [3]:
df = pd.read_csv(
    "../data/processed/news_dataset.csv"
)

df.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [4]:
df["content"] = (
    df["title"] 
    + " " 
    + df["text"]
)


df.head()

,title,text,subject,date,label,content
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0,Ben Stein Calls Out 9th Circuit Court: Committ...
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1,Trump drops Steve Bannon from National Securit...
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1,Puerto Rico expects U.S. to lift Jones Act shi...
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0,OOPS: Trump Just Accidentally Confirmed He Le...
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1,Donald Trump heads for Scotland to reopen a go...

In [5]:
stemmer = PorterStemmer()

stop_words = set(
    stopwords.words("english")
)

In [6]:
def clean_text(text):

    # lowercase
    text = text.lower()

    # remove URLs
    text = re.sub(
        r"http\S+|www\S+",
        "",
        text
    )


    # remove special characters
    text = re.sub(
        "[^a-zA-Z]",
        " ",
        text
    )


    # tokenize
    words = text.split()


    # remove stopwords + stemming
    words = [
        stemmer.stem(word)
        for word in words
        if word not in stop_words
    ]


    return " ".join(words)

In [7]:
sample = df["content"][0]

print("Before:")
print(sample[:500])


print("\nAfter:")
print(clean_text(sample)[:500])

Before:
Ben Stein Calls Out 9th Circuit Court: Committed a ‘Coup d’état’ Against the Constitution 21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washingto

After:
ben stein call th circuit court commit coup tat constitut st centuri wire say ben stein reput professor pepperdin univers also hollywood fame appear tv show film ferri bueller day made provoc statement judg jeanin pirro show recent discuss halt impos presid trump execut order travel stein refer judgement th circuit court washington state coup tat execut branch constitut stein went call judg seattl polit puppet judiciari polit pawn watch interview complet statement note stark contrast rhetor left

In [8]:
df["clean_content"] = df["content"].apply(
    clean_text
)

In [9]:
df[
    [
        "content",
        "clean_content",
        "label"
    ]
].head()

,content,clean_content,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,ben stein call th circuit court commit coup ta...,0
1,Trump drops Steve Bannon from National Securit...,trump drop steve bannon nation secur council w...,1
2,Puerto Rico expects U.S. to lift Jones Act shi...,puerto rico expect u lift jone act ship restri...,1
3,OOPS: Trump Just Accidentally Confirmed He Le...,oop trump accident confirm leak isra intellig ...,0
4,Donald Trump heads for Scotland to reopen a go...,donald trump head scotland reopen golf resort ...,1

In [10]:
df[
    [
        "clean_content",
        "label"
    ]

].to_csv(
    "../data/processed/cleaned_news.csv",
    index=False
)

In [11]:
import os

os.path.exists(
    "../data/processed/cleaned_news.csv"
)

True